### ISSUE TITLE
Allow for Hidden Wireless Networks

### ISSUE THREAD

**Issue by MrHamel** [BELABOX/belaUI#11]
In the BelaUI, I'd like the ability to manually enter in the SSID and password.

Primary use would be to force the system to connect to a Wi-Fi network should their be a parsing bug somewhere between the NetworkManager scan and BelaUI. An example would be forcing it to connect to an iPhone hotspot (see BVK2_Twitch's issue in #general-tech on Discord).

If someone is security conscious, they can also make use of the feature.

**Comment by rationalsa** [comment]
'Hidden' networks have nothing to do with security since one only needs to fire up monitor mode to find them. If there are parsing bugs in belaUI, I'll fix them. NM problems need to be reported upstream.
