### ISSUE TITLE
Allow for SSIDs with Spaces and Symbols

### ISSUE THREAD

**Issue by MrHamel** [BELABOX/belaUI#12]
According to Marlow in the Discord, not all SSIDs are parsable and shown in the UI, below is an attempted fix.

If there is a parsing issue with `nmcli`, I came up with the shell string:

`iwlist wlan0 scanning | grep Cell -A9 | grep -P "ESSID|Frequency|Encryption"`

Regexp to go along with it, supposedly compatible with JavaScript according to Regex101 when used with the global and multi-line flags:

`Frequency:(.*)\n.*Encryption key:(on|off)\n.*ESSID:\"(.*)\"`

(Regex101 Link) https://regex101.com/r/cSZXul/1

**Comment by rationalsa** [comment]
Can't reproduce. `Silly iPhone's SSID #` shows up in the scan results, I could create the connection, manually connect and disconnect from the network and delete it.

Please provide an ESSID that's not handled correctly.
