### ISSUE TITLE
rtt column?

### ISSUE THREAD

**Issue by b3ck** [BELABOX/belaUI#9]
Also would be good to have a column in the table for the connections next to bitrate what each connection is getting for RTT.

Kind Regards,
-b3ck

**Comment by b3ck** [comment]
![image](https://user-images.githubusercontent.com/1740542/145245756-be165d9d-efdc-4dc2-b6e9-1af9109e3d9a.png)

**Comment by rationalsa** [comment]
RTT isn't available on a per connection basis
